info:
	@echo "Building : "
	@echo " Target"
	@echo "  Directory $(TARGET)"
	@echo " Linux"
	@echo "  Version $(KVER)"
	@echo "  Config $(KCONFIG)"
	@echo "  Patches $(KPATCHES)"
	@echo "  Sources from $(KSRC)" 
	@echo "  Build Directory $(KDIR)"
	@echo "  Base Directory $(KDIRBASE)"
	@echo "  Archive $(KARCHIVE)"
	@echo "  Menuconfig $(MENUCONFIG)"
	@echo " Click"
	@echo "  Version $(CVER)"
	@echo "  Patches $(CPATCHES)"
	@echo "  Sources from $(CSRC)" 
	@echo "  Directory $(CDIR)"
	@echo " Xen"
	@echo "  Version $(XVER)"
	@echo " BusyBox"
	@echo "  Version $(BBVER)"
	@echo " Ixgbe"
	@echo "  Version $(IVER)"
	@echo " Bnx2"
	@echo "  Version $(B2VER)"


